// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5bwAVSS7yxRyYYekzZSF6R
// Component: O5sEW05m_bGM
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "./plasmic_copy_of_cardless_com.module.css"; // plasmic-import: 5bwAVSS7yxRyYYekzZSF6R/projectcss
import * as sty from "./PlasmicBenefitRow.module.css"; // plasmic-import: O5sEW05m_bGM/css

export type PlasmicBenefitRow__VariantMembers = {};

export type PlasmicBenefitRow__VariantsArgs = {};
type VariantPropType = keyof PlasmicBenefitRow__VariantsArgs;
export const PlasmicBenefitRow__VariantProps = new Array<VariantPropType>();

export type PlasmicBenefitRow__ArgsType = {
  header?: React.ReactNode;
  benefits?: React.ReactNode;
};

type ArgPropType = keyof PlasmicBenefitRow__ArgsType;
export const PlasmicBenefitRow__ArgProps = new Array<ArgPropType>(
  "header",
  "benefits"
);

export type PlasmicBenefitRow__OverridesType = {
  root?: p.Flex<"div">;
  copy29?: p.Flex<"div">;
};

export interface DefaultBenefitRowProps {
  header?: React.ReactNode;
  benefits?: React.ReactNode;
  className?: string;
}

function PlasmicBenefitRow__RenderFunc(props: {
  variants: PlasmicBenefitRow__VariantsArgs;
  args: PlasmicBenefitRow__ArgsType;
  overrides: PlasmicBenefitRow__OverridesType;
  dataFetches?: PlasmicBenefitRow__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"copy29"}
        data-plasmic-override={overrides.copy29}
        hasGap={true}
        className={classNames(projectcss.all, sty.copy29)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__h4B38
              )}
            >
              {"Modern banking"}
            </div>
          ),

          value: args.header,
          className: classNames(sty.slotTargetHeader)
        })}

        {p.renderPlasmicSlot({
          defaultContents:
            "Easily manage spending, payments, rewards, and so much more ",
          value: args.benefits,
          className: classNames(sty.slotTargetBenefits)
        })}
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "copy29"],
  copy29: ["copy29"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  copy29: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBenefitRow__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBenefitRow__VariantsArgs;
    args?: PlasmicBenefitRow__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicBenefitRow__Fetches;
  } & Omit<PlasmicBenefitRow__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBenefitRow__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBenefitRow__ArgProps,
      internalVariantPropNames: PlasmicBenefitRow__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicBenefitRow__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBenefitRow";
  } else {
    func.displayName = `PlasmicBenefitRow.${nodeName}`;
  }
  return func;
}

export const PlasmicBenefitRow = Object.assign(
  // Top-level PlasmicBenefitRow renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    copy29: makeNodeComponent("copy29"),

    // Metadata about props expected for PlasmicBenefitRow
    internalVariantProps: PlasmicBenefitRow__VariantProps,
    internalArgProps: PlasmicBenefitRow__ArgProps
  }
);

export default PlasmicBenefitRow;
/* prettier-ignore-end */
