// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5bwAVSS7yxRyYYekzZSF6R
// Component: ufZvdJ_v0tDv
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsbUUiKYc55Zpu } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: bUUiKYc55Zpu/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "./plasmic_copy_of_cardless_com.module.css"; // plasmic-import: 5bwAVSS7yxRyYYekzZSF6R/projectcss
import * as sty from "./PlasmicAppStoreCta.module.css"; // plasmic-import: ufZvdJ_v0tDv/css

export type PlasmicAppStoreCta__VariantMembers = {};

export type PlasmicAppStoreCta__VariantsArgs = {};
type VariantPropType = keyof PlasmicAppStoreCta__VariantsArgs;
export const PlasmicAppStoreCta__VariantProps = new Array<VariantPropType>();

export type PlasmicAppStoreCta__ArgsType = {};
type ArgPropType = keyof PlasmicAppStoreCta__ArgsType;
export const PlasmicAppStoreCta__ArgProps = new Array<ArgPropType>();

export type PlasmicAppStoreCta__OverridesType = {
  root?: p.Flex<"a"> & Partial<LinkProps>;
  img?: p.Flex<typeof p.PlasmicImg>;
};

export interface DefaultAppStoreCtaProps {
  className?: string;
}

function PlasmicAppStoreCta__RenderFunc(props: {
  variants: PlasmicAppStoreCta__VariantsArgs;
  args: PlasmicAppStoreCta__ArgsType;
  overrides: PlasmicAppStoreCta__OverridesType;
  dataFetches?: PlasmicAppStoreCta__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbUUiKYc55Zpu()
  });

  return (
    <p.PlasmicLink
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(projectcss.a, projectcss.root_reset, sty.root)}
      component={Link}
      href={"/ios" as const}
      platform={"nextjs"}
    >
      <p.PlasmicImg
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img)}
        displayHeight={
          hasVariant(globalVariants, "screen", "tablet")
            ? ("100%" as const)
            : hasVariant(globalVariants, "screen", "laptopSmall")
            ? ("100%" as const)
            : ("auto" as const)
        }
        displayMaxHeight={"none" as const}
        displayMaxWidth={"none" as const}
        displayMinHeight={"0" as const}
        displayMinWidth={"0" as const}
        displayWidth={
          hasVariant(globalVariants, "screen", "tablet")
            ? ("100%" as const)
            : hasVariant(globalVariants, "screen", "laptopSmall")
            ? ("100%" as const)
            : ("100%" as const)
        }
        src={{
          src: "/plasmic/copy_of_cardless_com/images/image2.svg",
          fullWidth: 300,
          fullHeight: 86,
          aspectRatio: 3.472222
        }}
      />
    </p.PlasmicLink>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "a";
  img: typeof p.PlasmicImg;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAppStoreCta__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAppStoreCta__VariantsArgs;
    args?: PlasmicAppStoreCta__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicAppStoreCta__Fetches;
  } & Omit<PlasmicAppStoreCta__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAppStoreCta__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAppStoreCta__ArgProps,
      internalVariantPropNames: PlasmicAppStoreCta__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicAppStoreCta__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAppStoreCta";
  } else {
    func.displayName = `PlasmicAppStoreCta.${nodeName}`;
  }
  return func;
}

export const PlasmicAppStoreCta = Object.assign(
  // Top-level PlasmicAppStoreCta renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicAppStoreCta
    internalVariantProps: PlasmicAppStoreCta__VariantProps,
    internalArgProps: PlasmicAppStoreCta__ArgProps
  }
);

export default PlasmicAppStoreCta;
/* prettier-ignore-end */
